myapp/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from myapp import  views
urlpatterns = [
url(r'^test/(\w+)',views.test, name="detail"),
    url(r'^login/',views.my_login),
    url(r'^hide/',views.hide),
    url(r'^register/',views.register),

    url(r'^download', views.download_file,name="download"),
    url(r'^collect',views.collect,name='collect'),
    url(r'^logout/$',views.userlogout, name = 'logout'),

]

mypictures/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myapp import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recharge/', views.recharge, name='recharge'),
    url(r'^home/', views.home, name="home"),
    url(r'^show/(\w+)', views.show),

    url(r'^myapp/', include('myapp.urls', namespace='myapp')),



    # /usercenter/
    url(r'usercenter/$', views.usercenter_index, name='index'),
    # /usercenter/upload
    url(r'usercenter/upload/$', views.upload, name='upload'),
    # /usercenter/edit
    url(r'^usercenter/edit/(.+)/$', views.edit, name='edit'),
    # usercenter/myfavorite
    url(r'usercenter/myfavorite/$', views.myfavorite, name='myfavorite'),
    # usercenter/recharge
    # url(r'recharge/$', views.recharge, name='recharge'),
    url(r'^usercenter/setnewversion/(.+)/$', views.set_ver_version, name='setnewversion'),
    url(r'^usercenter/deletepicture/(.+)/$', views.delete_picture, name='deletepicture'),
    url(r'^usercenter/cancelfavorite/(.+)/$', views.cancel_favorite, name='cancelfavorite'),
    url(r'^usercenter/handleupload/$', views.handle_upload, name='handleupload'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/usercenter/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心 - 编辑作品</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <!--[if lte IE 8]>
            <link rel="stylesheet" href="static/css/layouts/marketing-old-ie.css">
        <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/layouts/menu.css">
    <link rel="stylesheet" href="/static/css/layouts/header.css">
    <link rel="stylesheet" href="/static/css/layouts/mypics.css">
    <link rel="stylesheet" href="/static/css/layouts/gallery.css">

    <!--<![endif]-->
    <script type="text/javascript">
        function editPictureInfo() {
            var info_div = document.getElementById('PictureInfo');
            info_div.style.display = 'none';
            var edit_div = document.getElementById('EditInfo');
            edit_div.style.display = 'inline-block';
            var edit_btn = document.getElementById('startEdit');
            edit_btn.style.display = 'none';
            var confirm_btn = document.getElementById('confirmEdit');
            confirm_btn.style.display = 'inline-block';
            var cancel_btn = document.getElementById('cancel_btn');
            cancel_btn.style.display = 'inline-block';

        }

        function editSubmit() {
            var edit_form = document.getElementById('editForm');
            editForm.submit();
        }


        function cancel() {
            var info_div = document.getElementById('PictureInfo');
            info_div.style.display = 'inline-block';
            var edit_div = document.getElementById('EditInfo');
            edit_div.style.display = 'none';
            var edit_btn = document.getElementById('startEdit');
            edit_btn.style.display = 'inline-block';
            var confirm_btn = document.getElementById('confirmEdit');
            confirm_btn.style.display = 'none';
            var cancel_btn = document.getElementById('cancel_btn');
            cancel_btn.style.display = 'none';

        }
    </script>
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".photo-box").mouseover(function () {
                $(this).children(".photo-box-caption").show();
            });
            $(".photo-box").mouseout(function () {
                $(this).children(".photo-box-caption").hide();
            });
        });
    </script>
</head>
<body>
<div class="header">
    <div class="custom-menu-wrapper pure-menu-fixed pic-menu">
        <div class="home-menu pure-menu-horizontal pure-menu custom-menu custom-menu-top">
            <a href="{% url 'index' %}" class="pure-menu-heading custom-menu-brand">个人中心</a>
            <a href="#" class="custom-menu-toggle" id="toggle"><s class="bar"></s><s class="bar"></s></a>
        </div>
        <div class="pure-menu pure-menu-horizontal pure-menu-scrollable custom-menu custom-menu-bottom custom-menu-tucked"
             id="tuckedMenu">
            {#            <div class="custom-menu-screen"></div>#}
            <ul class="pure-menu-list pic-menu-heading">
                {#                <li class="pure-menu-item"><a href="{% url 'index' %}" class="pure-menu-link pic-menu-link">管理</a></li>#}
                <li class="pure-menu-item"><a href="{% url 'upload' %}" class="pure-menu-link pic-menu-link">上传</a></li>
                <li class="pure-menu-item"><a href="{% url 'myfavorite' %}" class="pure-menu-link pic-menu-link">收藏</a>
                </li>
                <li class="pure-menu-item"><a href="{% url 'recharge' %}" class="pure-menu-link pic-menu-link">充值</a>
                </li>
                <li class="pure-menu-item"><a href="/home/" class="pure-menu-link pic-menu-link">返回主站</a></li>
                <li class="pure-menu-item "><a href="/myapp/logout" class="pure-menu-link pic-menu-link"> 注销 </a></li>
            </ul>
        </div>
    </div>
</div>
<div class="banner-container pure-g">
    <div class="banner pure-u-1">
        <a>{{ picture.title }}</a>
    </div>
</div>
<div class="main-wrapper">
    <div class="main-content">
        <div class="recommend-line">
            <a>最新版本</a>
        </div>
        <div class="pure-g">
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-1-4"></div>
            <div class="work-wrapper pure-u-1 pure-u-md-3-5 pure-u-lg-1-2">
                {#        <h3>最新版本</h3>#}
                <div class="work-content">
                    <div class="work-main">
                        <img class="pure-img-responsive work-img" src="{{ newest_ver.original_picture.url }}">
                    </div>
                    <div class="work-side">
                        <div id="PictureInfo" style="width: 100%">
                            <div class="work-detail">
                                <div><a>标题</a> {{ picture.title }}</div>
                            </div>
                            <div class="work-tags">
                                <div class="work-tag"><a>分类</a> {{ picture.category }}</div>
                                <div class="work-tag"><a>价格</a> {{ picture.price }}</div>
                            </div>
                            <hr>
                            <div class="work-intro"><a>简介</a> {{ picture.description }}</div>
                            <hr>
                        </div>
                        <div id="EditInfo" style="width: 100% ;display: none">
                            <form class="pure-form pure-form-stacked" method="post" name="edit_info" id="editForm"
                                  enctype="multipart/form-data">{% csrf_token %}
                                <fieldset>
                                    <input class="pic-input" type="file" accept="image/*" name="new_version"
                                           id="updateimage">
                                    <label for="title">标题</label>
                                    <input class="pic-input" type="text" name="title" value="{{ picture.title }}">
                                    <label for="category">分类</label>
                                    <select class="pic-input" name="category" value="{{ picture.category }}">
                                        <option value="animation">动漫</option>
                                        <option value="food">美食</option>
                                        <option value="scenery">风景</option>
                                        <option value="people">人像</option>
                                        <option value="other">其它</option>
                                    </select>
                                    <label for="price">价格</label>
                                    <input class="pic-input" type="number" name="price" value="{{ picture.price }}">
                                    <label for="description">简介</label>
                                    <textarea class="pic-input" class="pure-input-1" type="text" name="description"
                                              value="{{ picture.description }}"></textarea>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                    <div class="work-button" style="margin-bottom: 0">
                        <button class="pure-button pure-button-primary pic-button" id="startEdit"
                                onclick="editPictureInfo()">编辑
                        </button>
                        <button class="fav-button pure-button pure-button-primary pic-button" id="confirmEdit"
                                style="display: none" onclick="editSubmit()">确定
                        </button>
                        <button class="dload-button pure-button pure-button-primary pic-button" id="cancel_btn"
                                style="display: none" onclick="cancel()">取消
                        </button>
                    </div>

                </div>

            </div>
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-1-4"></div>
        </div>
        <div class="recommend-line">
            <a>历史版本</a>
        </div>
        <div class="work-wrapper">
            <div class="work-content">
                <div class="pure-g" style="padding-top: 0.5em; padding-bottom: 0.5em">
                    {% for ver in versions %}
                        <div class="photo-box pure-u-1 pure-u-md-1-3 pure-u-lg-1-6 ">
                            <img src="{{ ver.original_picture.url }}">
                            <div class="photo-box-caption">
                                <div class="photo-button">
                                    <button class="new-button pure-button pure-button-primary pic-button"
                                            onclick="window.location.href='{% url 'setnewversion' ver.version_id %}'">
                                        设为最新
                                    </button>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

</div>
</div>
</body>
<script>
    (function (window, document) {
        document.getElementById('toggle').addEventListener('click', function (e) {
            document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
            document.getElementById('toggle').classList.toggle('x');
        });
    })(this, this.document);
</script>
</html>

templates/usercenter/myfavorite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心 - 收藏</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <!--[if lte IE 8]>
            <link rel="stylesheet" href="static/css/layouts/marketing-old-ie.css">
        <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/layouts/menu.css">
    <link rel="stylesheet" href="/static/css/layouts/header.css">
    <link rel="stylesheet" href="/static/css/layouts/mypics.css">
    <link rel="stylesheet" href="/static/css/layouts/gallery.css">
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".photo-box").mouseover(function () {
                $(this).children(".photo-box-caption").show();
            });
            $(".photo-box").mouseout(function () {
                $(this).children(".photo-box-caption").hide();
            });
        });
    </script>
    <!--<![endif]-->
</head>
<body>
<div class="header">
    <div class="custom-menu-wrapper pure-menu-fixed pic-menu">
        <div class="home-menu pure-menu-horizontal pure-menu custom-menu custom-menu-top">
            <a href="{% url 'index' %}" class="pure-menu-heading custom-menu-brand">个人中心</a>
            <a href="#" class="custom-menu-toggle" id="toggle"><s class="bar"></s><s class="bar"></s></a>
        </div>
        <div class="pure-menu pure-menu-horizontal pure-menu-scrollable custom-menu custom-menu-bottom custom-menu-tucked"
             id="tuckedMenu">
            {#            <div class="custom-menu-screen"></div>#}
            <ul class="pure-menu-list pic-menu-heading">
                {#                <li class="pure-menu-item"><a href="{% url 'index' %}" class="pure-menu-link pic-menu-link">管理</a></li>#}
                <li class="pure-menu-item"><a href="{% url 'upload' %}" class="pure-menu-link pic-menu-link">上传</a></li>
                <li class="pure-menu-item"><a href="{% url 'myfavorite' %}" class="pure-menu-link pic-menu-link">收藏</a>
                </li>
                <li class="pure-menu-item"><a href="{% url 'recharge' %}" class="pure-menu-link pic-menu-link">充值</a>
                </li>
                <li class="pure-menu-item"><a href="/home/" class="pure-menu-link pic-menu-link">返回主站</a></li>
                <li class="pure-menu-item "><a href="/myapp/logout" class="pure-menu-link pic-menu-link"> 注销 </a></li>
            </ul>
        </div>
    </div>
</div>
<div class="banner-container pure-g">
    <div class="banner pure-u-1">
        <a>收藏</a>
    </div>
</div>

<div class="main-wrapper">
    <div class="main-content">
        <div class="pure-g">
            {% for ver in ver_list %}
                <div class="photo-box pure-u-1 pure-u-md-1-3 pure-u-lg-1-6">
                    {#                    <a href="{% url 'myapp:detail' ver.version_id %}">#}
                    <img class="pure-img" src="{{ ver.watermark_picture.url }}">
                    <div class="photo-box-caption">
                        <aside>
                            {{ ver.picture.title }}
                        </aside>
                        <div class="photo-button">
                            <a class="edit-button pure-button" href="{% url 'myapp:detail' ver.version_id %}">详情</a>
                            <button class="delele-button pure-button pure-button-primary pic-button "
                                    onclick="window.location.href='{% url 'cancelfavorite' ver.picture.picture_id %}'">
                                取消收藏
                            </button>
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
</div>


</body>
<script>
    (function (window, document) {
        document.getElementById('toggle').addEventListener('click', function (e) {
            document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
            document.getElementById('toggle').classList.toggle('x');
        });
    })(this, this.document);
</script>
</html>

templates/usercenter/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心 - 上传</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <!--[if lte IE 8]>
            <link rel="stylesheet" href="static/css/layouts/marketing-old-ie.css">
        <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/layouts/menu.css">
    <link rel="stylesheet" href="/static/css/layouts/header.css">
    <link rel="stylesheet" href="/static/css/layouts/mypics.css">
    <link rel="stylesheet" href="/static/css/layouts/gallery.css">

    <!--<![endif]-->
</head>
<body>
<div class="header">
    <div class="custom-menu-wrapper pure-menu-fixed pic-menu">
        <div class="home-menu pure-menu-horizontal pure-menu custom-menu custom-menu-top">
            <a href="{% url 'index' %}" class="pure-menu-heading custom-menu-brand">个人中心</a>
            <a href="#" class="custom-menu-toggle" id="toggle"><s class="bar"></s><s class="bar"></s></a>
        </div>
        <div class="pure-menu pure-menu-horizontal pure-menu-scrollable custom-menu custom-menu-bottom custom-menu-tucked"
             id="tuckedMenu">
            {#            <div class="custom-menu-screen"></div>#}
            <ul class="pure-menu-list pic-menu-heading">
                {#                <li class="pure-menu-item"><a href="{% url 'index' %}" class="pure-menu-link pic-menu-link">管理</a></li>#}
                <li class="pure-menu-item"><a href="{% url 'upload' %}" class="pure-menu-link pic-menu-link">上传</a></li>
                <li class="pure-menu-item"><a href="{% url 'myfavorite' %}" class="pure-menu-link pic-menu-link">收藏</a>
                </li>
                <li class="pure-menu-item"><a href="{% url 'recharge' %}" class="pure-menu-link pic-menu-link">充值</a>
                </li>
                <li class="pure-menu-item"><a href="/home/" class="pure-menu-link pic-menu-link">返回主站</a></li>
                <li class="pure-menu-item "><a href="/myapp/logout" class="pure-menu-link pic-menu-link"> 注销 </a></li>
            </ul>
        </div>
    </div>
</div>
<div class="banner-container pure-g">
    <div class="banner pure-u-1">
        <a>上传</a>
    </div>
</div>
<div class="main-wrapper">
    <div class="main-content">
        <div class="pure-g">
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-8-24"></div>
            <div class="pure-u-1 pure-u-md-3-5 pure-u-lg-8-24">
                <form class="pure-form pure-form-stacked" action="{% url 'handleupload' %}" method="post"
                      id="upload_form"
                      name="upload_form"
                      enctype="multipart/form-data">{% csrf_token %}
                    <fieldset>

                        <input class="pic-input" type="file" accept="image/*" id="chooseImage" name="original">
                        <label for="title">标题</label>
                        <input class="pic-input" type="text" name="title">
                        <label for="category">分类</label>
                        <select class="pic-input" id="category" name="category">
                            <option value="animation">动漫</option>
                            <option value="food">美食</option>
                            <option value="scenery">风景</option>
                            <option value="people">人像</option>
                            <option value="other">其它</option>
                        </select>
                        <label for="price">价格</label>
                        <input class="pic-input" type="number" name="price">
                        <label for="description">简介</label>
                        <textarea class="pic-input" type="text" name="description"
                                  style="margin-bottom: 1em"></textarea>
                        <div style="text-align: center">
                            <button class="pure-button pure-button-primary pic-button" type="submit" value="上传">上传
                            </button>
                        </div>
                    </fieldset>


                </form>
            </div>
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-8-24"></div>
        </div>

    </div>
</div>
</body>
<script>
    (function (window, document) {
        document.getElementById('toggle').addEventListener('click', function (e) {
            document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
            document.getElementById('toggle').classList.toggle('x');
        });
    })(this, this.document);
</script>
</html>

templates/usercenter/usercenter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <!--[if lte IE 8]>
            <link rel="stylesheet" href="static/css/layouts/marketing-old-ie.css">
        <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/layouts/menu.css">
    <link rel="stylesheet" href="/static/css/layouts/header.css">
    <link rel="stylesheet" href="/static/css/layouts/mypics.css">
    <link rel="stylesheet" href="/static/css/layouts/gallery.css">
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".photo-box").mouseover(function () {
                $(this).children(".photo-box-caption").show();
            });
            $(".photo-box").mouseout(function () {
                $(this).children(".photo-box-caption").hide();
            });
        });
    </script>
    <!--<![endif]-->
</head>
<body>
<div class="header">
    <div class="custom-menu-wrapper pure-menu-fixed pic-menu">
        <div class="home-menu pure-menu-horizontal pure-menu custom-menu custom-menu-top">
            <a href="{% url 'index' %}" class="pure-menu-heading custom-menu-brand">个人中心</a>
            <a href="#" class="custom-menu-toggle" id="toggle"><s class="bar"></s><s class="bar"></s></a>
        </div>
        <div class="pure-menu pure-menu-horizontal pure-menu-scrollable custom-menu custom-menu-bottom custom-menu-tucked"
             id="tuckedMenu">
            {#            <div class="custom-menu-screen"></div>#}
            <ul class="pure-menu-list pic-menu-heading">
                {#                <li class="pure-menu-item"><a href="{% url 'index' %}" class="pure-menu-link pic-menu-link">管理</a></li>#}
                <li class="pure-menu-item"><a href="{% url 'upload' %}" class="pure-menu-link pic-menu-link">上传</a></li>
                <li class="pure-menu-item"><a href="{% url 'myfavorite' %}" class="pure-menu-link pic-menu-link">收藏</a>
                </li>
                <li class="pure-menu-item"><a href="{% url 'recharge' %}" class="pure-menu-link pic-menu-link">充值</a>
                </li>
                <li class="pure-menu-item"><a href="/home/" class="pure-menu-link pic-menu-link">返回主站</a></li>
                <li class="pure-menu-item "><a href="/myapp/logout" class="pure-menu-link pic-menu-link"> 注销 </a></li>
            </ul>
        </div>
    </div>
</div>
<div class="banner-container pure-g">
    <div class="banner pure-u-1">
        <a>Hello, {{ username }}</a>
    </div>
</div>

<div class="main-wrapper">
    <div class="main-content">
        <div class="pure-g">
            {% for ver in ver_list %}
                <div class="photo-box pure-u-1 pure-u-md-1-3 pure-u-lg-1-6">
                    <img class=" pure-img" src="{{ ver.original_picture.url }}">
                    <div class="photo-box-caption">
                        <aside>{{ ver.picture.title }}</aside>
                        <div class="photo-button">
                             <a class="edit-button pure-button"
                               href="{% url 'edit' ver.picture.picture_id %}">编辑</a>
                            <button class="delele-button pure-button pure-button-primary pic-button"
                                    onclick="window.location.href='{% url 'deletepicture' ver.picture.picture_id %}'">删除
                            </button>
                        </div>

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>

</body>

<script>
    (function (window, document) {
        document.getElementById('toggle').addEventListener('click', function (e) {
            document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
            document.getElementById('toggle').classList.toggle('x');
        });
    })(this, this.document);
</script>
</html>