myapp/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from myapp import  views
urlpatterns = [
url(r'^test/(\w+)',views.test, name="detail"),
    url(r'^login/',views.my_login),
    url(r'^hide/',views.hide),
    url(r'^register/',views.register),

    url(r'^download', views.download_file,name="download"),
    url(r'^collect',views.collect,name='collect'),
    url(r'^logout/$',views.userlogout, name = 'logout'),

]

mypictures/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myapp import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recharge/', views.recharge, name='recharge'),
    url(r'^home/', views.home, name="home"),
    url(r'^show/(\w+)', views.show),

    url(r'^myapp/', include('myapp.urls', namespace='myapp')),



    # /usercenter/
    url(r'usercenter/$', views.usercenter_index, name='index'),
    # /usercenter/upload
    url(r'usercenter/upload/$', views.upload, name='upload'),
    # /usercenter/edit
    url(r'^usercenter/edit/(.+)/$', views.edit, name='edit'),
    # usercenter/myfavorite
    url(r'usercenter/myfavorite/$', views.myfavorite, name='myfavorite'),
    # usercenter/recharge
    # url(r'recharge/$', views.recharge, name='recharge'),
    url(r'^usercenter/setnewversion/(.+)/$', views.set_ver_version, name='setnewversion'),
    url(r'^usercenter/deletepicture/(.+)/$', views.delete_picture, name='deletepicture'),
    url(r'^usercenter/cancelfavorite/(.+)/$', views.cancel_favorite, name='cancelfavorite'),
    url(r'^usercenter/handleupload/$', views.handle_upload, name='handleupload'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/hide.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>


</head>
<body>
<a href="/myapp/test/{{ picture_id }}">点我</a>

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <!--[if lte IE 8]>
            <link rel="stylesheet" href="static/css/layouts/marketing-old-ie.css">
        <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/layouts/menu.css">
    <link rel="stylesheet" href="/static/css/layouts/header.css">
    <link rel="stylesheet" href="/static/css/layouts/mypics.css">
    <link rel="stylesheet" href="/static/css/layouts/gallery.css">
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".photo-box").mouseover(function () {
                $(this).children(".photo-box-caption").show();
            });
            $(".photo-box").mouseout(function () {
                $(this).children(".photo-box-caption").hide();
            });
        });
    </script>
    <!--<![endif]-->
</head>
<body>
<div class="header">
    <div class="custom-menu-wrapper pure-menu-fixed">
        <div class="home-menu pure-menu-horizontal pure-menu custom-menu custom-menu-top">
            <a href="#" class="pure-menu-heading custom-menu-brand">MyPics</a>
            <a href="#" class="custom-menu-toggle" id="toggle"><s class="bar"></s><s class="bar"></s></a>
        </div>
        <div class="pure-menu pure-menu-horizontal pure-menu-scrollable custom-menu custom-menu-bottom custom-menu-tucked"
             id="tuckedMenu">
            {#            <div class="custom-menu-screen"></div>#}
            <ul class="pure-menu-list">
                <li class="pure-menu-item"><a href="/home" class="pure-menu-link">首页</a></li>
                <li class="pure-menu-item"><a href="/show/animation" class="pure-menu-link">动漫</a></li>
                <li class="pure-menu-item"><a href="/show/food" class="pure-menu-link">美食</a></li>
                <li class="pure-menu-item"><a href="/show/scenery" class="pure-menu-link">风景</a></li>
                <li class="pure-menu-item"><a href="/show/people" class="pure-menu-link">人像</a></li>
                <li class="pure-menu-item"><a href="/show/other" class="pure-menu-link">其它</a></li>
                {% ifequal username 'login' %}
                    <li class="pure-menu-item"><a href="/myapp/{{ username }}"
                                                  class="pure-menu-link"> {{ username }} </a></li>
                {% else %}
                    <li class="pure-menu-item"><a href="{% url 'index' %}" class="pure-menu-link"> {{ username }} </a>
                    </li>
                {% endifequal %}
                <li class="pure-menu-item"><a href="/myapp/logout" class="pure-menu-link"> 注销 </a></li>
            </ul>
        </div>
    </div>
</div>


<div class="splash-container">
    <div class="splash">
        <h1 class="splash-head">My Pictures</h1>
        <form class="pure-form" action="../home/" method="post">
            {% csrf_token %}
            {#            <label></label>#}
            <input type="text" name="content" class="pic-input"/>
            <button type="submit" class="pure-button pure-button-primary pic-button">搜 索</button>
        </form>

    </div>
</div>

<div class="content-wrapper">
    <div class="content">
        <div class="recommend-line">
            <a>最新</a>
        </div>
        <div class="pure-g">
            {% for v in newlist %}
                <a class="photo-box pure-u-1 pure-u-md-1-3 pure-u-lg-1-6" href="/myapp/test/{{ v.id }}">
                    <img src="{{ v.pic }}" alt="error">
                    <div class="photo-box-caption"><aside>{{ v.title }}</aside></div>
                </a>
            {% endfor %}
        </div>
    </div>

    <div class="content">
        <div class="recommend-line">
            <a>最热</a>
        </div>
        <div class="pure-g">
            {% for v in hotlist %}
                <a class="photo-box pure-u-1 pure-u-md-1-3 pure-u-lg-1-6" href="/myapp/test/{{ v.id }}">
                    <img src="{{ v.pic }}" alt="error">
                    <div class="photo-box-caption"><aside>{{ v.title }}</aside></div>
                </a>
            {% endfor %}
        </div>
    </div>

    <div class="content">
        <div class="recommend-line">
            <a>全部</a>
        </div>
        <div class="pure-g">
            {% for v in alllist %}
                <a class="photo-box pure-u-1 pure-u-md-1-3 pure-u-lg-1-6" href="/myapp/test/{{ v.id }}">
                    <img src="{{ v.pic }}" alt="error">
                    <div class="photo-box-caption"><aside>{{ v.title }}</aside></div>
                </a>
            {% endfor %}
        </div>
    </div>

</div>

</body>

<script>
    (function (window, document) {
        document.getElementById('toggle').addEventListener('click', function (e) {
            document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
            document.getElementById('toggle').classList.toggle('x');
        });
    })(this, this.document);
</script>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <!--[if lte IE 8]>
            <link rel="stylesheet" href="static/css/layouts/marketing-old-ie.css">
        <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/layouts/menu.css">
    <link rel="stylesheet" href="/static/css/layouts/header.css">
    <link rel="stylesheet" href="/static/css/layouts/mypics.css">
    <link rel="stylesheet" href="/static/css/layouts/gallery.css">

    <!--<![endif]-->
</head>
<body>
<div class="header">
    <div class="custom-menu-wrapper pure-menu-fixed pic-menu">
        <div class="home-menu pure-menu-horizontal pure-menu custom-menu custom-menu-top">
            <a href="#" class="pure-menu-heading custom-menu-brand">MyPics</a>
            <a href="#" class="custom-menu-toggle" id="toggle"><s class="bar"></s><s class="bar"></s></a>
        </div>
        <div class="pure-menu pure-menu-horizontal pure-menu-scrollable custom-menu custom-menu-bottom custom-menu-tucked"
             id="tuckedMenu">
            {#            <div class="custom-menu-screen"></div>#}
            <ul class="pure-menu-list pic-menu-heading">
                <li class="pure-menu-item "><a href="/home" class="pure-menu-link pic-menu-link">首页</a></li>
                <li class="pure-menu-item "><a href="/show/animation" class="pure-menu-link pic-menu-link">动漫</a></li>
                <li class="pure-menu-item"><a href="/show/food" class="pure-menu-link pic-menu-link">美食</a></li>
                <li class="pure-menu-item "><a href="/show/scenery" class="pure-menu-link pic-menu-link">风景</a></li>
                <li class="pure-menu-item "><a href="/show/people" class="pure-menu-link pic-menu-link">人像</a></li>
                <li class="pure-menu-item "><a href="/show/other" class="pure-menu-link pic-menu-link">其它</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="banner-container pure-g">
    <div class="banner pure-u-1">
        <a>登录</a>
    </div>
</div>

<div class="main-wrapper">
    <div class="main-content">
        <div class=" pure-g">
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-8-24"></div>
            <div class="pure-u-1 pure-u-md-3-5 pure-u-lg-8-24">
                {% if errors %}

                    {% for error in errors %}
                        <p style="color: red;">
                            {{ error }}
                        </p>
                    {% endfor %}

                {% endif %}

                <form class="pure-form pure-form-stacked" action="" method="post">{% csrf_token %}
                    <fieldset>
                        <input class="pic-input" type='text' placeholder="用户名" name='account'>
                        <input class="pic-input" type='password' placeholder="密码" name='password'>
                        <div style="text-align: center">
                            <button type='submit' class="pure-button pure-button-primary pic-button" placeholder="Login"
                                    value="登录">登录
                            </button>
                        </div>
                    </fieldset>
                </form>
                <div style="text-align: center">
                    <a href="/myapp/register">
                        <button class="pure-button pure-button-primary pic-button">注册</button>
                    </a>
                </div>
            </div>
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-8-24"></div>
        </div>
    </div>
</div>


</body>


<script>
    (function (window, document) {
        document.getElementById('toggle').addEventListener('click', function (e) {
            document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
            document.getElementById('toggle').classList.toggle('x');
        });
    })(this, this.document);
</script>
</html>

templates/recharge.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心 - 充值</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <!--[if lte IE 8]>
            <link rel="stylesheet" href="static/css/layouts/marketing-old-ie.css">
        <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/layouts/menu.css">
    <link rel="stylesheet" href="/static/css/layouts/header.css">
    <link rel="stylesheet" href="/static/css/layouts/mypics.css">
    <link rel="stylesheet" href="/static/css/layouts/gallery.css">

    <!--<![endif]-->
</head>
<body>
<div class="header">
    <div class="custom-menu-wrapper pure-menu-fixed pic-menu">
        <div class="home-menu pure-menu-horizontal pure-menu custom-menu custom-menu-top">
            <a href="{% url 'index' %}" class="pure-menu-heading custom-menu-brand">个人中心</a>
            <a href="#" class="custom-menu-toggle" id="toggle"><s class="bar"></s><s class="bar"></s></a>
        </div>
        <div class="pure-menu pure-menu-horizontal pure-menu-scrollable custom-menu custom-menu-bottom custom-menu-tucked"
             id="tuckedMenu">
            {#            <div class="custom-menu-screen"></div>#}
            <ul class="pure-menu-list pic-menu-heading">
                {#                <li class="pure-menu-item"><a href="{% url 'index' %}" class="pure-menu-link pic-menu-link">管理</a></li>#}
                <li class="pure-menu-item"><a href="{% url 'upload' %}" class="pure-menu-link pic-menu-link">上传</a></li>
                <li class="pure-menu-item"><a href="{% url 'myfavorite' %}" class="pure-menu-link pic-menu-link">收藏</a>
                </li>
                <li class="pure-menu-item"><a href="{% url 'recharge' %}" class="pure-menu-link pic-menu-link">充值</a>
                </li>
                <li class="pure-menu-item"><a href="/home/" class="pure-menu-link pic-menu-link">返回主站</a></li>
                <li class="pure-menu-item "><a href="/myapp/logout" class="pure-menu-link pic-menu-link"> 注销 </a></li>
            </ul>
        </div>
    </div>
</div>
<div class="banner-container pure-g">
    <div class="banner pure-u-1">
        <a>充值</a>
    </div>
</div>
<div class="main-wrapper">
    <div class="main-content">
        <div class="pure-g">
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-8-24"></div>
            <div class="pure-u-1 pure-u-md-3-5 pure-u-lg-8-24">
                <form class="pure-form" action="../recharge/" method="post">
                    <fieldset>
                        {% csrf_token %}
                        <h4> 账户余额：{{ balance }} 豆豆</h4>
                        <label>账户名 <input class="pic-input " type="text" name="user_id"/> </label>

                        <div class="pure-g">
                            <label class="pure-u-1-2"><input class="recharge" name="query" type="radio" value=50
                                                             required/>
                                50豆豆/10元 </label>
                            <label class="pure-u-1-2"><input class="recharge" name="query" type="radio" value=100
                                                             required/>
                                100豆豆/20元</label>
                            <label class="pure-u-1-2"><input class="recharge" name="query" type="radio" value=200
                                                             required/>
                                200豆豆/38元 </label>
                            <label class="pure-u-1-2"><input class="recharge" name="query" type="radio" value=300
                                                             required/>
                                300豆豆/55元 </label>
                        </div>

                        <div class="pure-u-1 usr-button" style="text-align: center;margin-top:1.5em">
                            <button class="pure-button pure-button-primary pic-button" onclick="myFunction()"
                                    type="submit"
                                    class="btn btn-info">
                                充值
                            </button>
                        </div>

                    </fieldset>
                </form>
            </div>

            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-8-24"></div>

        </div>
    </div>

</div>
</body>
<script>
    (function (window, document) {
        document.getElementById('toggle').addEventListener('click', function (e) {
            document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
            document.getElementById('toggle').classList.toggle('x');
        });
    })(this, this.document);
</script>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <!--[if lte IE 8]>
            <link rel="stylesheet" href="static/css/layouts/marketing-old-ie.css">
        <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/layouts/menu.css">
    <link rel="stylesheet" href="/static/css/layouts/header.css">
    <link rel="stylesheet" href="/static/css/layouts/mypics.css">
    <link rel="stylesheet" href="/static/css/layouts/gallery.css">

    <!--<![endif]-->
</head>
<body>
<div class="header">
    <div class="custom-menu-wrapper pure-menu-fixed pic-menu">
        <div class="home-menu pure-menu-horizontal pure-menu custom-menu custom-menu-top">
            <a href="#" class="pure-menu-heading custom-menu-brand">MyPics</a>
            <a href="#" class="custom-menu-toggle" id="toggle"><s class="bar"></s><s class="bar"></s></a>
        </div>
        <div class="pure-menu pure-menu-horizontal pure-menu-scrollable custom-menu custom-menu-bottom custom-menu-tucked"
             id="tuckedMenu">
            {#            <div class="custom-menu-screen"></div>#}
            <ul class="pure-menu-list pic-menu-heading">
                <li class="pure-menu-item "><a href="/home" class="pure-menu-link pic-menu-link">首页</a></li>
                <li class="pure-menu-item "><a href="/show/animation" class="pure-menu-link pic-menu-link">动漫</a></li>
                <li class="pure-menu-item"><a href="/show/food" class="pure-menu-link pic-menu-link">美食</a></li>
                <li class="pure-menu-item "><a href="/show/scenery" class="pure-menu-link pic-menu-link">风景</a></li>
                <li class="pure-menu-item "><a href="/show/people" class="pure-menu-link pic-menu-link">人像</a></li>
                <li class="pure-menu-item "><a href="/show/other" class="pure-menu-link pic-menu-link">其它</a></li>
                <li class="pure-menu-item "><a href="/myapp/login" class="pure-menu-link pic-menu-link"> login </a></li>
            </ul>
        </div>
    </div>
</div>
<div class="banner-container pure-g">
    <div class="banner pure-u-1">
        <a>注册</a>
    </div>
</div>

<div class="main-wrapper">
    <div class="main-content">
        <div class="pure-g">
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-8-24"></div>
            <div class="pure-u-1 pure-u-md-3-5 pure-u-lg-8-24">
                {% if errors %}
                    <li>

                        {% for error in errors %}
                            <p style="color: red;">
                                {{ error }}
                            </p>
                        {% endfor %}
                    </li>
                {% endif %}

                <form class="pure-form pure-form-stacked" action="" method="post">{% csrf_token %}
                    <fieldset>
                        <input class="pic-input" type='text' placeholder="用户名" name='account'>
                        <input class="pic-input" type='password' placeholder="密码" name='password'>
                        <input class="pic-input" type='password' placeholder="确认密码" name='password2'>
                        <div style="text-align: center">
                            <button class="pure-button pure-button-primary pic-button" type='submit' placeholder="Login"
                                    value="登录">注册
                            </button>
                        </div>

                    </fieldset>
                </form>
            </div>
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-8-24"></div>
        </div>
    </div>
</div>


</body>


<script>
    (function (window, document) {
        document.getElementById('toggle').addEventListener('click', function (e) {
            document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
            document.getElementById('toggle').classList.toggle('x');
        });
    })(this, this.document);
</script>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <!--[if lte IE 8]>
            <link rel="stylesheet" href="static/css/layouts/marketing-old-ie.css">
        <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/layouts/menu.css">
    <link rel="stylesheet" href="/static/css/layouts/header.css">
    <link rel="stylesheet" href="/static/css/layouts/mypics.css">
    <link rel="stylesheet" href="/static/css/layouts/gallery.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!--<![endif]-->
</head>

<body>
<div class="header">
    <div class="custom-menu-wrapper pure-menu-fixed pic-menu">
        <div class="home-menu pure-menu-horizontal pure-menu custom-menu custom-menu-top">
            <a href="#" class="pure-menu-heading custom-menu-brand">MyPics</a>
            <a href="#" class="custom-menu-toggle" id="toggle"><s class="bar"></s><s class="bar"></s></a>
        </div>
        <div class="pure-menu pure-menu-horizontal pure-menu-scrollable custom-menu custom-menu-bottom custom-menu-tucked"
             id="tuckedMenu">
            {#            <div class="custom-menu-screen"></div>#}
            <ul class="pure-menu-list pic-menu-heading">
                <li class="pure-menu-item "><a href="/home" class="pure-menu-link pic-menu-link">首页</a></li>
                <li class="pure-menu-item "><a href="/show/animation" class="pure-menu-link pic-menu-link">动漫</a></li>
                <li class="pure-menu-item"><a href="/show/food" class="pure-menu-link pic-menu-link">美食</a></li>
                <li class="pure-menu-item "><a href="/show/scenery" class="pure-menu-link pic-menu-link">风景</a></li>
                <li class="pure-menu-item "><a href="/show/people" class="pure-menu-link pic-menu-link">人像</a></li>
                <li class="pure-menu-item "><a href="/show/other" class="pure-menu-link pic-menu-link">其它</a></li>
                {% ifequal username 'login' %}
                    <li class="pure-menu-item ">
                        <a href="/myapp/{{ username }}" class="pure-menu-link pic-menu-link"> {{ username }} </a>
                    </li>
                {% else %}
                    <li class="pure-menu-item "><a href="{% url 'index' %}"
                                                   class="pure-menu-link pic-menu-link"> {{ username }} </a>
                    </li>
                {% endifequal %}
                <li class="pure-menu-item "><a href="/myapp/logout" class="pure-menu-link pic-menu-link"> 注销 </a></li>
            </ul>
        </div>
    </div>
</div>
<div class="banner-container pure-g">
    <div class="banner pure-u-1">
        <a>{{ title }}</a>
    </div>
</div>
<div class="main-wrapper">
    <div class="main-content">
        <div class="pure-g">
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-1-4"></div>
            <div class="work-wrapper pure-u-1 pure-u-md-3-5 pure-u-lg-1-2">
                <div class="work-content">
                    <div class="work-button">
                        {#                     <i class="fa fa-search-plus"></i>#}
                        <button class="fav-button pure-button pure-button-primary pic-button"
                                onclick="window.location.href='{% url 'myapp:collect' %}'">收藏
                        </button>
                        <button class="dload-button pure-button pure-button-primary pic-button" onclick="myFunction()">
                            下载
                        </button>

                    </div>
                    <div class="work-main">
                        <img class="pure-img-responsive work-img" src={{ path }}>
                    </div>
                    <div class="work-side">
                        <div class="work-detail">
                            <div><a>标题</a> {{ title }}</div>
                            <div><a>作者</a> {{ author }}</div>
                        </div>
                        <div class="work-tags">
                            <div class="work-tag"><a>分类</a> {{ category }}</div>
                            <div class="work-tag"><a>收藏</a> {{ favourite }}</div>
                            <div class="work-tag"><a>价格</a> {{ price }}</div>
                        </div>
                        <hr>
                        <div class="work-intro"><a>简介</a> {{ description }}</div>
                        <hr>
                    </div>
                </div>
            </div>
            <div class="pure-u-1 pure-u-md-1-5 pure-u-lg-1-4"></div>
        </div>
    </div>

</div>
</div>


</body>
</html>
<script>
    (function (window, document) {
        document.getElementById('toggle').addEventListener('click', function (e) {
            document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
            document.getElementById('toggle').classList.toggle('x');
        });
    })(this, this.document);
</script>
<script>
    function myFunction() {
        var opt ={{ is_download|safe }};
        var r;
        var price ={{ price|safe }};
        var is_login ={{ is_login|safe }};
        var is_myself ={{ is_myself|safe }};
        if (is_myself == 0) {

            if (is_login == 1) {
                if (opt == 0) {
                    r = confirm("确认要下载吗,将花费" + price);
                }
                else {
                    r = confirm("您已下载过该图片，一个月内可以免费重复下载")
                }
                var pid ={{ p_id|safe }};
                if (r == true) {
                    window.location.href = '{% url 'myapp:download' %}';
                }
                else {
                    window.location.href = '/myapp/test/' + pid;
                }
            }
            else {
                alert('请先登录');
                window.location.href = '/myapp/login';
            }
        }
        else {
            if (is_login == 1) {
                window.location.href = '{% url 'myapp:download' %}';
            }
            else {
                alert('请先登录');
                window.location.href = '/myapp/login';
            }
        }
    }</script>